### ISSUE TITLE
IntelliJ Idea Glassfish plugin not working with 7.0.18

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#25188]
## Environment Details
* GlassFish Version (and build number): 7.0.18

----------

## Problem Description

IntelliJ cannot deploy applications for GlassFish and gives a `NoSuchMethodError` exception:

``
Error running admin process:
Message: java.lang.NoSuchMethodError: 'void com.sun.enterprise.admin.remote.RemoteResponseManager.<init>(java.io.InputStream, int, java.util.logging.Logger)' Stack trace: com.intellij.javaee.process.common.JavaeeProcessUtilException: java.lang.NoSuchMethodError: 'void com.sun.enterprise.admin.remote.RemoteResponseManager.<init>(java.io.InputStream, int, java.util.logging.Logger)' at com.intellij.javaee.process.common.MethodInvocator.invoke(MethodInvocator.java:47) at com.intellij.javaee.oss.process.JavaeeProcess.processRequest(JavaeeProcess.java:110) at com.intellij.javaee.oss.process.JavaeeProcess.run(JavaeeProcess.java:53) at com.intellij.javaee.oss.process.JavaeeProcess.main(JavaeeProcess.java:32) Caused by: java.lang.NoSuchMethodError: 'void com.sun.enterprise.admin.remote.RemoteResponseManager.<init>(java.io.InputStream, int, java.util.logging.Logger)' at com.intellij.javaee.oss.glassfish.agent.Glassfish31AgentBase.doParseResponse(Glassfish31AgentBase.java:21) at com.intellij.javaee.oss.glassfish.agent.Glassfish3AgentBase.parseResponse(Glassfish3AgentBase.java:195) at com.intellij.javaee.oss.glassfish.agent.Glassfish3AgentBase.invoke(Glassfish3AgentBase.java:144) at com.intellij.javaee.oss.glassfish.agent.Glassfish3AgentBase.doConnect(Glassfish3AgentBase.java:34) at com.intellij.javaee.oss.agent.SimpleAgentBase$1.doJob(SimpleAgentBase.java:24) at com.intellij.javaee.oss.agent.SimpleAgentBase$1.doJob(SimpleAgentBase.java:20) at com.intellij.javaee.oss.agent.SimpleAgentJob.perform(SimpleAgentJob.java:12) at com.intellij.javaee.oss.agent.SimpleAgentBase.connect(SimpleAgentBase.java:33) at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) at java.base/java.lang.reflect.Method.invoke(Method.java:580) at com.intellij.javaee.process.common.MethodInvocator.invoke(MethodInvocator.java:41) ... 3 more
```

## Steps to reproduce

1. Install the GlassFish plugin into IntelliJ
2. Install GlassFish 7.0.18 into IntelliJ
3. Create a sample Jakarta EE application
4. Run the application with GlassFish 7.0.18

IntelliJ is able to start GlassFish but fails to deploy the application with the `NoSuchMethodError` exception above.

## Impact of Issue

Not possible to use GlassFish 7.0.18 from IntelliJ.

[//]: # "Please choose one each Type, Component, and Priority label"
Type: Bug
Component: Deployment, IDE support
Priority: High

**Comment by OndroMih** [comment]
It seems that there was a breaking change in the `RemoteResponseManager` class in the following commit: https://github.com/eclipse-ee4j/glassfish/commit/6c6a55c0c4bf460dcdb592d2eabf5bdb3a5f7528. This introduced a new charset argument in the constructor.

A simple fix would bring back the previous constructor, which would delegate to the new constructor with the default charset. This constructor should be marked as Deprecated, encouraging the IntelliJ GlassFish plugin to switch to the new constructor. However, it's important that the old constructor remains to avoid breaking older versions of the IntelliJ plugin.
